const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uuid=()=>window.crypto&&crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16)});
let busy=0,saving=0,C,mute=0,z=10,N='',AGE=0,G='',cur=0,reach=0,SW,T0,ID=uuid(),tabTimers=[];
const snd=(f,d=.12,t='square',g=.06,f2)=>{if(mute||!C)return;const T=C.currentTime,o=C.createOscillator(),v=C.createGain();o.type=t;o.frequency.setValueAtTime(f,T);if(f2)o.frequency.exponentialRampToValueAtTime(f2,T+d);v.gain.setValueAtTime(g,T);v.gain.exponentialRampToValueAtTime(.001,T+d);o.connect(v);v.connect(C.destination);o.start();o.stop(T+d)};
const pop=()=>snd(500,.1,'square',.06,900),ok=()=>snd(700,.08,'triangle'),err=()=>{snd(200,.25,'sawtooth',.08,120);setTimeout(()=>snd(160,.3,'sawtooth',.08,90),180)},yay=()=>[523,659,784,1047].forEach((f,i)=>setTimeout(()=>snd(f,.2,'triangle',.07),i*120));
const Q=[
[2,"s","ما وضعك الأساسي حاليًا؟ (اختر خيارًا واحدًا، وإن كنت تدرس وتعمل معًا اختر «طالب»)|What is your main current situation? (choose one; if you both study and work, choose \"Student\")","طالب (مدرسة أو جامعة)|Student (school or university);معلم أو معلمة|Teacher;أعمل في المجال الحكومي|I work in the government sector;أعمل في المجال الخاص|I work in the private sector;أعمل في المجال الصحي (طبيب، ممرض، أخصائي، فني، إداري في منشأة صحية)|I work in the healthcare field (doctor, nurse, specialist, technician, admin staff in a health facility);أعمل في خدمة العملاء (بنك، مطار، متجر، مركز اتصال...)|I work in customer service (bank, airport, store, call center...);أعمل في مجال آخر (حدد)|I work in another field (please specify)|o;لا أدرس ولا أعمل حاليًا|Currently neither studying nor working"],
[3,"s","هل لديك إعاقة سمعية؟|Do you have a hearing impairment?","لا (سامع)|No (hearing);نعم (أصم أو ضعيف سمع)|Yes (Deaf or hard of hearing)"],
[4,"s","هل سبق لك التعامل مع شخص أصم؟|Have you ever interacted with a Deaf person?","نعم|Yes;لا|No"],
[5,"s","(إن كانت الإجابة نعم) ما علاقتك به؟|(If yes) What is your relationship with the Deaf person?","فرد من الأسرة|Family member;صديق|Friend;زميل عمل أو دراسة|Classmate or coworker;عميل أو مراجع|Customer or client;أخرى|Other|o"],
[6,"m","هل سبق لك تعلم لغة الإشارة أو محاولة تعلمها؟|Have you ever learned or tried to learn sign language?","لا، لم أحاول من قبل|No, I have never tried;نعم، عبر فيديوهات (يوتيوب وغيره)|Yes, through videos (YouTube, etc.);نعم، من خلال دورة أو مركز|Yes, through a course or training center;نعم، عبر تطبيق|Yes, through an application;نعم، من شخص أعرفه|Yes, from someone I know;حاولت لكن توقفت قبل أن أتقنها|I tried but stopped before mastering it;أخرى|Other|o"],
[7,"r","ما مدى اهتمامك بتعلم لغة الإشارة السعودية؟|How interested are you in learning Saudi Sign Language?","غير مهتم إطلاقًا|Not interested at all;مهتم جدًا|Very interested"],
[8,"m","ما الأسباب التي قد تشجعك على تعلمها؟|What reasons might encourage you to learn it?","التواصل مع صديق أو قريب أصم|Communicating with a Deaf friend or relative;الدراسة أو العمل|Study or work;الخدمات العامة|Public services;مهارة جديدة|A new skill;اهتمام شخصي|Personal interest;مسؤولية اجتماعية وتطوع|Social responsibility and volunteering;أخرى|Other|o"],
[9,"m","ما أكبر العوائق التي قد تمنعك من تعلمها؟|What are the biggest barriers that might stop you from learning it?","قلة الوقت|Lack of time;عدم توفر مصادر سعودية|Lack of Saudi resources;صعوبة التعلم بدون مدرب|Difficulty learning without an instructor;لا أعرف من أين أبدأ|I don't know where to start;لا أرى حاجة فعلية|I don't see a real need;أخرى|Other|o"],
[10,"m","كيف تفضل تعلمها؟|How would you prefer to learn it?","فيديوهات تعليمية|Educational videos;دروس تقليدية|Traditional lessons;تطبيق تعليمي|Educational application;لعبة تفاعلية|Interactive game;ممارسة بالكاميرا|Camera-based practice;أخرى|Other|o"],
[11,"r","ما مدى رغبتك في تعلم لغة الإشارة السعودية من خلال تطبيق يعتمد على اللعب التعليمي (نقاط، مستويات، تحديات)؟|How interested would you be in learning Saudi Sign Language through a game-based app (points, levels, challenges)?","غير راغب إطلاقًا|Not interested at all;راغب جدًا|Very interested"],
[12,"r","ما مدى أهمية أن تتمكن من متابعة تقدمك ومعرفة الإشارات التي أتقنتها والتي تحتاج إلى ممارسة؟|How important is it for you to track your progress and know which signs you have mastered and which need more practice?","غير مهم|Not important;مهم جدًا|Very important"],
[13,"s","كم من الوقت تستطيع تخصيصه في الجلسة الواحدة؟|How much time could you spend learning in one session?","أقل من 10 دقائق|Less than 10 minutes;10–20 دقيقة|10–20 minutes;أكثر من 20 دقيقة|More than 20 minutes"],
[14,"s","كم مرة في الأسبوع تتوقع أن تتعلم؟|How often would you expect to learn per week?","يوميًا|Daily;3–4 مرات|3–4 times a week;مرة أو مرتين|Once or twice a week;عند الحاجة فقط|Only when needed"],
[15,"r","ما احتمال أن توصي بتطبيق كهذا لأصدقائك أو أسرتك؟|How likely are you to recommend such an app to your friends or family?","غير محتمل إطلاقًا|Very unlikely;محتمل جدًا|Very likely"],
[16,"t","ما أكثر شيء تتمنى وجوده في تطبيق لتعلم لغة الإشارة السعودية؟|What would you most like to see in a Saudi Sign Language learning application?",""]];
const QM={};Q.forEach(q=>QM[q[0]]=q);
const ops=q=>q[3]?q[3].split(';').map(s=>s.split('|')):[];
const SEC=[[2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16]];
const get=id=>{const k=QM[id][1];if(k=='r'){const b=$(`#q${id} .on`);return b?+b.dataset.v:0}if(k=='t')return $(`#q${id} textarea`).value.trim();const c=$$(`#q${id} input:checked`).map(x=>+x.value);return k=='s'?(c.length?c[0]:-1):c};
const vis=id=>id!=5||get(4)==0;
const valid=id=>{const k=QM[id][1],v=get(id);return k=='s'?v>=0:k=='m'?v.length>0:k=='r'?v>0:true};
const ans=(id,s='، ')=>{const q=QM[id],k=q[1],v=get(id),o=ops(q);if(k=='r')return v?v+'/5':'—';if(k=='t')return v||'—';const t=[].concat(v<0?[]:v).map(i=>{let s=o[i][0];if(o[i][2]){const x=$(`#q${id} .ot`).value.trim();if(x)s+=': '+x}return s});return t.join(s)||'—'};
const URL_='https://script.google.com/macros/s/AKfycbyMtKurV4BvE5NA7tOaJZhAANeiZp5TM9a_ChZVfuN4mIMjRla4PS6WO0C6m0FlKM2N/exec';// ضعي رابط Apps Script Web App المنتهي بـ /exec
const ageG=()=>AGE<18?'12–17':AGE<25?'18–24':AGE<35?'25–34':AGE<45?'35–44':'45 أو أكثر';
function pay(st){const answers={};SEC.slice(0,reach+1).forEach(s=>s.forEach(id=>{answers[String(id)]=vis(id)?(QM[id][1]==='r'?String(get(id)||''):ans(id,',').replace(/^—$/,'')):''}));return {id:ID,saveToken:uuid(),startTime:T0.toISOString(),endTime:st==='in_progress'?'':new Date().toISOString(),name:N,age:AGE,ageGroup:ageG(),gender:G,status:st,answers}}
function lockSurvey(on){saving=on?1:0;if(!SW)return;const description=SW.querySelector('#ds');if(description){if(on)description.textContent='جارٍ حفظ إجاباتك…';else if(description.dataset.description)description.innerHTML=description.dataset.description}SW.querySelectorAll('.bd button,.bd input,.bd textarea').forEach(el=>{if(on){el.dataset.wasDisabled=el.disabled?'1':'0';el.disabled=true}else if(el.dataset.wasDisabled!==undefined){el.disabled=el.dataset.wasDisabled==='1';delete el.dataset.wasDisabled}})}
let pendingSave=null,saveWorkerRunning=false;
function saveStatus(text){$('#savehint').textContent=text}
function enqueueSave(p){return new Promise(resolve=>{if(pendingSave)pendingSave.resolve(false);pendingSave={p,resolve};saveStatus('جارٍ حفظ إجاباتك…');void runSaveQueue()})}
async function runSaveQueue(){if(saveWorkerRunning)return;saveWorkerRunning=true;try{while(pendingSave){const job=pendingSave;pendingSave=null;let saved=false;try{saved=await send(job.p)}catch(e){}if(!pendingSave)saveStatus(saved?'تم حفظ إجاباتك ✓':'تعذّر الحفظ مؤقتًا — ستُعاد المحاولة مع الإرسال التالي');job.resolve(saved)}}finally{saveWorkerRunning=false}}
const save=(st,next)=>{if(saving)return;const p=pay(st);if(st==='in_progress'){void enqueueSave(p);if(next)next();return}enqueueSave(p).then(saved=>{if(!saved)retry(p,null)}).catch(()=>retry(p,null));if(next)next()};
function confirmSaved(id,token,ms=10000){return new Promise(resolve=>{let delay=300,done=false,retryTimer=null,cancelRequest=()=>{};const deadline=setTimeout(()=>finish(false),ms);function finish(value){if(done)return;done=true;clearTimeout(deadline);clearTimeout(retryTimer);cancelRequest();resolve(value)}function check(){if(done)return;const cb='banan_cb_'+Math.random().toString(36).slice(2,12).replace(/[^a-z0-9]/g,'');const script=document.createElement('script');let settled=false,requestTimer;function cleanup(){clearTimeout(requestTimer);delete window[cb];script.remove()}cancelRequest=()=>{settled=true;cleanup()};function respond(r){if(settled||done)return;settled=true;cleanup();if(r&&r.ok&&r.exists&&r.saveToken===token)return finish(true);delay=Math.min(delay+200,900);retryTimer=setTimeout(check,delay)}window[cb]=respond;script.onerror=()=>respond(null);requestTimer=setTimeout(()=>respond(null),6000);script.src=URL_+'?action=status&id='+encodeURIComponent(id)+'&callback='+cb+'&t='+Date.now();document.head.append(script)}check()})}
async function send(p,n=0){if(!URL_||URL_.includes('PASTE_APPS_SCRIPT'))return true;try{fetch(URL_,{method:'POST',mode:'no-cors',cache:'no-store',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(p)}).catch(()=>{})}catch(e){}if(await confirmSaved(p.id,p.saveToken))return true;if(n<2){await new Promise(r=>setTimeout(r,500*(n+1)));return send(p,n+1)}return false}
function retry(p,next){const w=win('تعذّر الحفظ','<p class="dm">😅 ما قدرنا نحفظ إجاباتك الحين، وإجاباتك ما زالت عندك. جرّب مرة ثانية.<small>We could not save right now. Your answers are safe here, please try again.</small></p><button class="btn" type="button">حاول مرة أخرى</button>',{c:'sm er',s:err,z:5000,x:w=>{w.remove();lockSurvey(false)}});w.querySelector('.btn').onclick=()=>{w.querySelector('.btn').disabled=true;enqueueSave(p).then(ok=>{if(ok){w.remove();lockSurvey(false);if(next)next()}else{w.remove();retry(p,next)}}).catch(()=>{w.remove();retry(p,next)})}}

function win(t,b,o={}){const w=document.createElement('div');w.className='win '+(o.c||'');w.style.zIndex=o.z||++z;w.innerHTML=`<div class="tb"><span>${t}</span><i><u>_</u><u>□</u><u class="x" role="button" aria-label="إغلاق">✕</u></i></div><div class="bd">${b}</div>`;w.querySelector('.x').onclick=()=>o.x?o.x(w):nox();$('#desk').append(w);(o.s||pop)();return w}
function dlg(m,bad=1,en=''){const w=win(bad?'Error':'تنبيه',`<p class="dm">${bad?'🚫':'💡'} ${m}<small>${en}</small></p><button class="btn" type="button">OK</button>`,{c:'sm'+(bad?' er':''),s:bad?err:ok,z:5000,x:w=>w.remove()});w.querySelector('.btn').onclick=()=>w.remove()}
const nox=()=>dlg('!عذرًا 🙈 ما نقدر نسكّر هذه النافذة قبل لا تكمّلها',1,"Sorry! We can't close this window until you finish it");
function icon(l,f,c=''){const b=document.createElement('button');b.className='ico '+c;b.type='button';b.innerHTML=`<svg width="56" height="64" viewBox="0 0 56 64"><path d="M6 4h30l14 14v42H6z" fill="#fff" stroke="#1b1b1b" stroke-width="3" stroke-linejoin="round"/><path d="M36 4v14h14" fill="#ffd84d" stroke="#1b1b1b" stroke-width="3" stroke-linejoin="round"/><path d="M14 30h28M14 40h28M14 50h18" stroke="#2aa3c4" stroke-width="3"/></svg><br>${l}`;if(c==='n'){b.querySelector('svg').innerHTML='<path d="M8 4h40v56H8z" fill="#fff5cf" stroke="#1b1b1b" stroke-width="3"/><path d="M8 4h40v12H8z" fill="#ff6f61" stroke="#1b1b1b" stroke-width="3"/><path d="M16 25h24M16 35h24M16 45h16" stroke="#1b1b1b" stroke-width="3"/>';b.querySelector('svg').setAttribute('aria-hidden','true')}b.onclick=f;$('#ic').append(b);return b}
const I1=$('#startFile');I1.onclick=()=>{try{C=C||new(window.AudioContext||window.webkitAudioContext)();if(C&&C.state==='suspended')C.resume()}catch(e){}if(busy)return;busy=1;load()};
$('#mu').onclick=function(){mute=!mute;this.textContent=mute?'🔇':'🔊'};
let openAnswers=null;const mn=$('#mn');$('#stb').onclick=e=>{e.stopPropagation();ok();mn.style.display=mn.style.display==='block'?'none':'block'};document.addEventListener('click',()=>mn.style.display='none');
$('#m1').onclick=()=>dlg('بنان تطبيق لتعلّم لغة الإشارة السعودية بأسلوب تفاعلي وممتع، وهذا الاستبيان يساعدنا نفهم احتياجك 💙',0,'Banan helps you learn Saudi Sign Language in an interactive, fun way, and this survey helps us understand your needs.');
$('#m2').onclick=()=>dlg('الاستبيان يأخذ نحو 5 دقائق، وإجاباتك سرية وللبحث فقط 🔒',0,'About 5 minutes. Your answers are confidential and for research only.');
$('#m3').onclick=()=>{if(openAnswers)openAnswers()};
const tick=()=>$('#clk').textContent=new Date().toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'});tick();if(!URL_||URL_.includes('PASTE_APPS_SCRIPT'))$('#savehint').textContent='وضع معاينة — اربطي Google Sheets قبل النشر';setInterval(tick,20000);
const PH=[['نحرّك أيدينا استعدادًا للسلام 👋','Warming up our hands to say hello'],['نرتّب الإشارات في أماكنها ✋','Putting the signs in their places'],['جاهزون لنعرف رأيك 💙','Ready for your thoughts']];
function load(){const w=win('جارٍ التحميل…','<svg width="40" height="32" viewBox="0 0 40 32" style="display:block" aria-hidden="true"><path d="M3 5h12l3 4h19v20H3z" fill="#ffd84d" stroke="#1b1b1b" stroke-width="3" stroke-linejoin="round"/></svg><p class="dm" id="lt"></p><small id="le"></small><div class="pb"><b id="lb"></b></div>');let p=0;const t=setInterval(()=>{p+=5;const k=p<40?0:p<80?1:2;$('#lt').textContent=PH[k][0];$('#le').textContent=PH[k][1];$('#lb').style.width=p+'%';if(p>=100){clearInterval(t);w.remove();hello()}},100)}
function hello(){const w=win('رسالة جديدة ',`<p class="dm"><b>!وصلتك رسالة من بنان</b><br>عرّفنا عليك قبل لا نبدأ، وما راح ياخذ منك إلا دقايق ✨</p><label class="fl"><span class="lb"><b>الاسم <em>(يقبل اسمًا مستعارًا)</em></b><small>Name (nickname is fine)</small></span><input type="text" id="nm" maxlength="40" autocomplete="off"></label><label class="fl"><span class="lb"><b>العمر</b><small>Age</small></span><input type="number" id="ag" min="12" step="1" inputmode="numeric"></label><div class="lb"><b>الجنس</b><small>Gender</small></div><div class="gc"><label class="gb"><input type="radio" name="g" value="ذكر"><svg width="30" height="32" viewBox="0 0 44 48" aria-hidden="true"><circle cx="22" cy="12" r="9" fill="#ffd84d" stroke="#1b1b1b" stroke-width="3"/><path d="M6 46v-10a8 8 0 0 1 8-8h16a8 8 0 0 1 8 8v10z" fill="#3a5fcd" stroke="#1b1b1b" stroke-width="3" stroke-linejoin="round"/></svg><span>ذكر<small>Male</small></span></label><label class="gb"><input type="radio" name="g" value="أنثى"><svg width="30" height="32" viewBox="0 0 44 48" aria-hidden="true"><circle cx="22" cy="12" r="9" fill="#ffd84d" stroke="#1b1b1b" stroke-width="3"/><path d="M22 24 8 46h28z" fill="#ff6f61" stroke="#1b1b1b" stroke-width="3" stroke-linejoin="round"/></svg><span>أنثى<small>Female</small></span></label></div><p class="cs">إجاباتك سرية وتُستخدم لأغراض البحث فقط، وبالضغط على OK فأنت توافق على المشاركة.</p><button class="btn" id="go" type="button" disabled>OK</button>`,{c:'hw'});
const chk=()=>{$('#go').disabled=!($('#nm').value.trim()&&$('#ag').value&&$('input[name=g]:checked'))};w.addEventListener('input',chk);w.addEventListener('change',chk);$('#go').onclick=()=>{const n=$('#nm').value.trim(),a=+$('#ag').value,g=($('input[name=g]:checked')||{}).value;if(!n||!a||!g)return dlg('عبّئ الاسم والعمر والجنس أولًا 🙂',0);if(a<12)return dlg('الاستبيان لمن هم 12 سنة فأكثر، شكرًا لاهتمامك 💛',0,'This survey is for ages 12 and above. Thank you for your interest!');if(!Number.isInteger(a))return dlg('اكتب العمر بالسنوات كرقم صحيح 🙂',0,'Please enter your age as a whole number of years.');N=n;AGE=a;G=g;T0=new Date();ID=uuid();w.remove();ok();survey()}}
function qh(id){const q=QM[id],[a,e]=q[2].split('|'),k=q[1],o=ops(q);let h=`<div class="q" id="q${id}"${id==5?' style="display:none"':''}><b><i class="nb">${id}</i>${a}</b><small>${e}</small>`;
if(k=='t')h+='<small class="keep">اختياري / Optional</small><textarea rows="3"></textarea>';
else if(k=='r')h+=`<div class="sc2">${[1,2,3,4,5].map(n=>`<button type="button" class="sc" data-v="${n}">${n}</button>`).join('')}</div><div class="ends"><span>1 = ${o[0][0]}<small>${o[0][1]}</small></span><span>5 = ${o[1][0]}<small>${o[1][1]}</small></span></div>`;
else h+=o.map((x,i)=>`<label class="op"><input type="${k=='s'?'radio':'checkbox'}" name="n${id}" value="${i}"> ${x[0]}<small>${x[1]}</small></label>`).join('')+(o.some(x=>x[2])?'<input type="text" class="ot" placeholder="حدد / Specify" style="display:none">':'');
return h+'</div>'}
const short=()=>esc(N.length>20?N.slice(0,20)+'…':N);
function survey(){const mob=matchMedia('(max-width:600px)').matches,n=short(),T=['1 عنك','2 رأيك','3 وقتك'],D=[`يا ${n}، عرّفنا على تجربتك مع لغة الإشارة`,`يا ${n}، قل لنا رأيك بصراحة، ما فيه إجابة خاطئة`,`يا ${n}، آخر قسم! وقتك وأمنياتك`];
const w=SW=win(mob?'استبيان بنان 👋':`أهلًا يا ${n} 👋 — استبيان بنان`,`<div class="tabs">${T.map(t=>`<button type="button">${t}</button>`).join('')}</div><div class="panes">${SEC.map((s,i)=>`<div class="pane">${s.map(id=>qh(id)).join('')}</div>`).join('')}</div><div class="ft sf"><button class="btn" id="bk" type="button">رجوع</button><div class="pb"><b id="pg"></b></div><button class="btn" id="okb" type="button">OK</button></div>`,{c:'sv'+(mob?' noen':'')});document.body.classList.add('insv');
const bi=w.querySelector('.tb i'),mt=document.createElement('u'),tg=document.createElement('u');mt.textContent=mute?'🔇':'🔊';mt.title='الصوت';mt.onclick=()=>{$('#mu').click();mt.textContent=mute?'🔇':'🔊'};tg.textContent='🌐 English';tg.title='English';tg.className='tg'+(mob?' pulse':' act');let tip=null;if(mob){tip=document.createElement('div');tip.className='tip';tip.innerHTML='تبغى الإنجليزي؟ اضغط هنا 👆<small>Need English? Tap here</small>';w.append(tip);setTimeout(()=>tip&&tip.remove(),7000)}tg.onclick=()=>{w.classList.toggle('noen');tg.classList.toggle('act',!w.classList.contains('noen'));tg.classList.remove('pulse');if(tip){tip.remove();tip=null}};bi.prepend(tg);bi.prepend(mt);
cur=0;reach=0;
const show=i=>{cur=i;$$('.pane').forEach((p,k)=>p.style.display=k==i?'block':'none');$$('.tabs button').forEach((b,k)=>b.className=(k==i?'on ':'')+(k>reach?'lk':''));$('#pg').style.width=(i+1)*100/3+'%';$('#pg').textContent=(i+1)+'/3';$('#bk').style.visibility=i?'visible':'hidden';$('.panes').scrollTop=0};
tabTimers=[];$$('.tabs button').forEach((b,k)=>{tabTimers.push(setTimeout(()=>{b.style.visibility='visible';pop()},250*(k+1)));b.onclick=()=>k>reach?dlg('أكمل القسم الحالي أولًا 🙂',1,'Finish the current section first'):(ok(),show(k))});
show(0);
$('#bk').onclick=()=>{ok();show(cur-1)};
$('#okb').onclick=()=>{if(saving)return;const section=cur,miss=SEC[section].filter(id=>vis(id)&&!valid(id));if(miss.length){w.classList.remove('sh');void w.offsetWidth;w.classList.add('sh');return dlg('ناقصك الإجابة عن: '+miss.join('، '),1,'Please answer the missing questions')}
if(section===0&&get(3)===1){reach=0;tabTimers.forEach(clearTimeout);$$('.tabs button').slice(1).forEach(b=>b.style.visibility='hidden');save('screened_out',()=>fin(1));return}if(section===2){reach=2;save('complete',()=>fin(0));return}ok();reach=Math.max(reach,section);save('in_progress',()=>{reach=Math.max(reach,section+1);show(section+1)})}}
document.addEventListener('change',e=>{const t=e.target,q=t.closest('.q');if(t.type==='radio'||t.type==='checkbox')snd(t.checked?760:480,.07,'triangle',.07);if(!q)return;const id=+q.id.slice(1);
if(id==6){const cs=$$('#q6 input[type=checkbox]');if(t.value==0&&t.checked)cs.forEach(c=>{if(c!=t)c.checked=false});else if(t.checked)cs[0].checked=false}
const ot=q.querySelector('.ot');if(ot){const oi=ops(QM[id]).findIndex(o=>o[2]),c=q.querySelector(`input[value="${oi}"]`);ot.style.display=c&&c.checked?'block':'none'}
if(id==4)$('#q5').style.display=get(4)==0?'block':'none'});
document.addEventListener('click',e=>{const b=e.target.closest('.sc');if(!b)return;b.parentNode.querySelectorAll('.on').forEach(x=>x.className='sc');b.className='sc on';ok()});
function fin(d){const TX=ntext(),NM=N,LB=short();SW.remove();document.body.classList.remove('insv');ok();const w=win('جارٍ الحفظ…','<p class="dm">جارٍ حفظ إجاباتك على سطح المكتب…<small>Saving your answers to the desktop…</small></p><div class="pb"><b id="sv"></b></div>',{x:()=>{}});let p=0;const t=setInterval(()=>{p+=20;$('#sv').style.width=p+'%';if(p>=100){clearInterval(t);w.remove();I1.disabled=true;I1.classList.add('finished');I1.title='اكتملت المشاركة';const answersFile=icon('إجاباتي',()=>notes(TX,NM),'n');answersFile.id='answersFile';openAnswers=()=>notes(TX,NM);$('#m3').style.display='block';answersFile.setAttribute('aria-label','فتح ملف إجاباتي');pop();busy=1;thanks(d)}},120)}
function thanks(d){const n=esc(N),h=[10,35,60,85].map((l,i)=>`<span class="ht" style="left:${l}%;animation-delay:${i*.6}s">♥</span>`).join('');
const w=win('فريق بنان 💙',`<div class="tkh"><span class="av">💙<i class="dot"></i></span><div><b>فريق بنان</b><span class="onl">● متصل الآن · Online</span></div></div><div class="cht"><div class="bub tk"><p><b>شكرًا لك يا ${n} 💙</b></p><p>وقتك ورأيك صاروا جزءًا من بنان، وبفضلك نقرّب خطوة من تطبيق يخلّي التواصل مع مجتمع الصم أسهل وأقرب للجميع.</p>${d?'<p>شكرًا لاهتمامك! هذا الاستبيان موجّه حاليًا للأشخاص السامعين.</p>':''}<p>يومك سعيد، ولا تنسَ تلوّح لنا بيدك 👋<br>— فريق بنان</p></div><div class="bub tk en2" dir="ltr"><p>Thank you, <bdi>${n}</bdi> 💙 Your time and thoughts are now part of Banan, and thanks to you we are one step closer to an app that makes communicating with the Deaf community easier for everyone.${d?' This survey currently targets hearing participants.':''} Have a lovely day, and do not forget to wave! 👋 — The Banan Team</p></div></div>${h}<div class="acts"><button class="btn" id="sh" type="button">أرسل لصديق 💌</button><button class="btn alt" id="cl" type="button">إغلاق</button></div>`,{c:'nd',s:yay,x:w=>w.remove()});
w.querySelector('#cl').onclick=()=>w.remove();
w.querySelector('#sh').onclick=()=>{const t='شاركت في استبيان بنان عن تعلّم لغة الإشارة السعودية، وأبغى رأيك أنت كمان 💙',u=location.href.split(/[?#]/)[0],cs=!!navigator.share;const s=win('أرسل لصديق 💌',`<p class="sp">شارك رابط الاستبيان مع من تحب 💙</p><div class="sg3${cs?' c3':''}"><a class="btn sb" target="_blank" rel="noopener" href="https://wa.me/?text=${encodeURIComponent(t+' '+u)}"><i>💬</i>واتساب</a><button class="btn sb" id="cp" type="button"><i>🔗</i>نسخ الرابط</button>${cs?'<button class="btn sb" id="ns" type="button"><i>📤</i>مشاركة</button>':''}</div><p class="cm" id="cm"></p>`,{c:'sm sw',z:5000,x:w=>w.remove()});if(cs)s.querySelector('#ns').onclick=()=>navigator.share({text:t+' '+u}).catch(()=>{});s.querySelector('#cp').onclick=()=>(navigator.clipboard||{writeText:()=>Promise.reject()}).writeText(u).then(()=>s.querySelector('#cm').textContent='تم النسخ ✨',()=>s.querySelector('#cm').textContent=u)};}
function ntext(){let t=`إجابات ${N} — استبيان بنان\n${new Date().toLocaleDateString('ar-SA')}\n\nالاسم: ${N}\nالعمر: ${AGE} (${ageG()})\nالجنس: ${G}\n`;SEC.slice(0,reach+1).forEach(s=>s.forEach(id=>{if(vis(id))t+=`\n${id}. ${QM[id][2].split('|')[0]}\n   ← ${ans(id)}\n`}));return t}
function notes(t,nm){win(`إجابات ${esc(nm.length>20?nm.slice(0,20)+'…':nm)}.txt`,`<div class="mn">File &nbsp; Edit &nbsp; View</div><pre>${esc(t)}</pre><div class="ft"><button class="btn" id="dl" type="button">حفظ نسخة على جهازي</button></div>`,{c:'np',x:w=>w.remove()});$('#dl').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+t.replace(/\n/g,'\r\n')],{type:'text/plain;charset=utf-8'}));a.download='إجاباتي-'+nm.replace(/[\\\/:*?\"<>|]/g,'').slice(0,20)+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),999);ok()}}

I1.disabled=false;$('#startStatus').hidden=true;
